FROM ubuntu:20.04

RUN apt-get -yqq update
RUN apt-get -yqq install python3-pip 
RUN apt-get -yqq install python3-dev 
RUN apt-get -yqq install curl 
RUN apt-get -yqq install gnupg
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt-get install -yq nodejs
